apiVersion: batch/v1
kind: Job
metadata:
  name: argocd-server-post-upgrade
  annotations:
    "helm.sh/hook": post-upgrade
spec:
  template:
    spec:
      containers:
      - name: argocd-server-post-upgrade
        image: alpine
        command: ["/bin/sh", "-c"]
        args:
        - |
          sleep 10  # Wait for the new deployment to stabilize
          EXTERNAL_IP=$(kubectl get svc argo-cd-argocd-server -n argocd -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          kubectl patch svc argo-cd-argocd-server -n argocd -p '{"spec": {"externalIPs": ["'"192.168.39.201'"]}}'
      restartPolicy: OnFailure

